# Generated by Django 5.2.5 on 2025-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
