# Generated by Django 5.2.5 on 2025-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
