# Generated by Django 5.2.5 on 2025-10-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRequest',
        ),
    ]
