# Generated by Django 5.2.5 on 2025-10-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
