# Generated by Django 5.2.5 on 2025-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicircleapp', '0004_remove_profile_is_approved_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unapproved_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
